#!/bin/bash

if [ -z "$1" ] ; then
    printf "Check out adback.co panel to get your token.\n\n"
    printf "\nUsage: ${0} [token] -c -a -html\n"
    exit 1
fi

FILE=$(wget -qO- https://adback.co/api/script/me?access_token=$1\&_format=yml)

if [ -z "$FILE" ] ; then
    printf "\nCan't access to  https://adback.co/api/script/me?access_token=${1}&_format=yml\n\n"
    printf "Please verifying this step:\n"
    printf "	1) Is your token valid ?                 ->  wget https://adback.co/api/doc?access_token=${1}\n"
    printf "	2) Are our servers reachable ?           ->  ping adback.co\n"
    printf "	3) Check out docs for the latest version ->  https://docs.adback.co/en/latest/\n\n"
    exit 1
fi

analytics_domain=$(echo $FILE | tr " " "\n" | awk '/analytics_domain/{getline; print}')

analytics_script_name=$(echo $FILE | tr " " "\n" | awk '/analytics_script/{getline; print}')

message_domain=$(echo $FILE | tr " " "\n" | awk '/message_domain/{getline; print}')

message_script_name=$(echo $FILE | tr " " "\n" | awk '/message_script/{getline; print}')

if [ -z "$analytics_domain" ] || [ -z "$analytics_script_name" ] || [ -z "$message_domain" ] \
    || [ -z "$message_script_name" ] ; then
    printf "\nWrong api datas, please try again later.\n\n"
    printf "Check out docs for the latest version -> https://docs.adback.co/en/latest/\n\n"
    exit 1
fi

#Analytics script js
A=$(cat <<EOF
(function (a,d){var s,t;s=d.createElement('script');
s.src=a;s.async=1;
t=d.getElementsByTagName('script')[0];
t.parentNode.insertBefore(s,t);
})("https://${analytics_domain}/${analytics_script_name}.js", document);
EOF
)

# Custom message script js
M=$(cat <<EOF
(function (a,d){var s,t,u;s=d.createElement(‘script’);
if(d.referrer){u=d.createElement('a');u.href=d.referrer;a=a+u.hostname;}
s.src=a;s.async=1;
t=d.getElementsByTagName('script')[0];
t.parentNode.insertBefore(s,t);
})("https://${message_domain}/${message_script_name}.js?ref=", document);
EOF
)


if [[ $2 == "-html" ]] || [[ $3 == "-html" ]] || [[ $4 == "-html" ]]; then
    A='<script>'$A'</script>'
    M='<script>'$M'</script>'
fi

if [[ $2 == "-c" ]] || [[ $3 == "-c" ]] || [[ $4 == "-c" ]]; then
    echo $M
fi

if [[ $2 == "-a" ]] || [[ $3 == "-a" ]] || [[ $4 == "-a" ]]; then
    echo $A
fi
